### ISSUE TITLE
Question about code coverage

### ISSUE THREAD

**Issue by Stegnerd** [VMadalin/kotlin-sample-app#15]
## Description
Can you elaborate on how you exclude the app directory from your code coverage in codecov?

## Basic Information

-   Device type: Android
-   OS version:
-   App version: latest

## Details
I see that in your diagram you don't have things like SampleMainActivity tested because they are excluded from the graph? 

![image](https://user-images.githubusercontent.com/12737758/76791927-46e00d80-6798-11ea-9894-aa56f2d6d9f8.png)

I was wonder how you did this because I see no ignore flags in your codecov/config.yml nor are there any exclusions in your jacoco configurations, at least that I can find!

Thanks!

**Comment by VMadalin** [comment]
Thank you so much for your question @Stegnerd. and my apologise for the delay.

Basically, all projects have added the gradle `jacoco` plugin: 
```
com.vanniktech:gradle-android-junit-jacoco-plugin
```
But exactly as you mention some of them don't have the test directory and that make to exclude them from the final coverage, like  `:app` module:

<img width="345" alt="Screenshot 2020-03-22 at 16 33 36" src="https://user-images.githubusercontent.com/18151158/77254743-e3078a00-6c5a-11ea-9c1c-8e33ff58e127.png">

Moreover for example on the `:commons` module contains the test directory but I exclude one class `NavigationExtensions.class` from coverage because it's a google workaround and I decide to don't test it hoping in someday they fit it. 

```java
junitJacoco {
    excludes = listOf("**/extensions/NavigationExtensions*.*")
}
```

**Comment by Stegnerd** [comment]
Thank you for the clarification! I couldn't figure that out that before. I understand how that removes the section now. Thanks again for the great learning tool!
