### ISSUE TITLE
No cancellation method for coroutines

### ISSUE THREAD

**Issue by abalta** [VMadalin/kotlin-sample-app#16]
First off all, thank you for this great repository with latest Android frameworks. I noticed that there is no cancel call for coroutine scopes. Is this caused for memory leaks?

**Comment by VMadalin** [comment]
First of all, @abalta thank you for your question and you are right the project has a memory leak. It's because of the workaround implemented by google for support `Navigation Component supports multiple back stacks`  here are the [issue](https://issuetracker.google.com/issues/127932815).

Basically the implementation is not the best and we still waiting for some android native solution to solve this. Regard the coroutines scopes I don't cancel them because I use the `viewModelScope` having implemented by default the `close()` method

```java
override fun close() {
        coroutineContext.cancel()
}
```

Please let me know what do you think. Thank you  :)
