### ISSUE TITLE
PayPal donation link doesn't work.

### ISSUE THREAD

**Issue by ofir-bar** [VMadalin/kotlin-sample-app#18]
## Description
PayPal donation link doesn't work.
Please update the PayPal link at FUNDING.yml
Thank you

**Comment by VMadalin** [comment]
Hi @ofir-bar. First of all thanks for your issue. You are right it's wrong because I change it in this time :). I appreciate your interest on the donation, but I created this project in terms of inspire people to combine different new technologies on android with a modular architecture. Designing in this way scalable, maintainable and last but least testable. Obviously, nothing is perfect and this project isn't. Are a lot of things to improve and iteration for me is the key. 

I'll be more than happy if this one helps you to inspire/apply some of the practices used for you current or next project ;)

**Comment by ofir-bar** [comment]
Oh.. be sure my friend, this helps a ton for me.
Thank you
